### PR TITLE
(PE-35979) resolve logging issues

### PR DESCRIPTION
**Pull request by jonathannewman**
This updates the version of logback to the latest.  This is necessary for the jetty integration to work correctly. It also reenables the MDC log converter and handler and injects them into the requests.

One test was updated to include more bytes in the response.  This seems to be new things that Jetty 10 is including that Jetty 9 did not, and didn't appear to be harmful.

### CODE REVIEW

**Comment by jonathannewman** [comment]
Actually it looks like the number of bytes in the response depend on the version of the jdk.  Going to update that test to be less sensitive.

**Comment by rileynewton** [comment]
Did you want to keep around the the MDC files under the disabled-java folder?

**Comment by jonathannewman** [comment]
Those were supposed to be removed.  Git wasn't working well with my attempts to `git mv` them for some reason.  I'll remove them.

**Comment by jonathannewman** [comment]
They could all be removed, so I did. :)

**Review by rileynewton — APPROVED** [review]
👍 
image

**Pull request merged**
