### PR TITLE
(PE-36261) Update README for Jetty10

### PR DESCRIPTION
**Pull request by rileynewton**

### CODE REVIEW

**Comment by jonathannewman** [comment]
We should update the changelog too with the initial version and a brief statement about what state we think it is in.

**Comment by jonathannewman** [comment]
There are some references in the `add-websocket-handler` that mention it being experimental.  I think we should remove those now.

**Comment by jonathannewman** [comment]
The support section at the bottom of the README should remove mentions of Jira and suggest using GitHub issues.

**Comment by rileynewton** [comment]
Whoops I missed a lot, think I got all that now.

**Review by jonathannewman — APPROVED** [review]

**Pull request merged**
